# Generated by Django 2.1 on 2018-08-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20180822_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apidata',
            name='id',
        ),
        migrations.AlterField(
            model_name='apidata',
            name='Id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
