# Generated by Django 2.1 on 2018-08-22 20:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20180822_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='Id',
            field=models.UUIDField(default=uuid.UUID('d57c8efc-488e-41e5-b8ec-731784417811'), editable=False, primary_key=True, serialize=False),
        ),
    ]
