# Generated by Django 2.1 on 2018-08-22 20:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20180822_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='Id',
            field=models.UUIDField(default=uuid.UUID('67d7ef72-2f95-4f25-b237-1c184607283c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
