# Generated by Django 2.1 on 2018-08-22 21:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20180822_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='Id',
            field=models.UUIDField(default=uuid.UUID('bc2f53cd-28ab-4dd1-8a0a-264948a145e7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
