# Generated by Django 2.1 on 2018-08-22 21:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20180822_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='Id',
            field=models.UUIDField(default=uuid.UUID('d6b0e4f1-a7cb-4248-8a81-e8658bf231e2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
