# Generated by Django 2.1 on 2018-08-24 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20180822_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apidata',
            name='Id',
        ),
        migrations.AddField(
            model_name='apidata',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e63a85b9-2ecf-4341-80fe-728ba9e411b6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
